apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: local-storage
  namespace: openshift-local-storage
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: node-role.kubernetes.io/worker
        operator: Exists

  storageClassDevices:
  - storageClassName: local-sc
    devicePaths:
    - /dev/sdb
